name: Feature request
description: Request a feature / improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / use-case
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Expected impact (outputs, speed, stability)
